### ISSUE TITLE
Add prefix param to the star macro

### ISSUE THREAD

**Issue by camerondavison** [dbt-labs/dbt-utils#409] opened 2021-09-03 17:16 UTC
### Describe the feature
Sometimes when you want to include all of the columns of another table it can be useful to prefix them all as well with something. So that if I include a pets table the table may have the columns `name,age` and you may want to join it to a people table that also hase `name,age` and you want to end up with a result that is `name,age,pet_name,pet_age` or something like that.

### Describe alternatives you've considered
Alternatively you have to reimplement the star macro by iterating all the columns and adding the prefix.

### Are you interested in contributing this feature?
I created a patch of the star command,  to work with my postgres db, so I would be willing to contribute it. I would need help knowing how to test it on multiple databases using the code base.

**Comment by joellabes** [comment] 2021-11-09 23:19
I think that this is a dupe of #436 so I'm going to close it out! Let me know if that's not the case.

**Comment by joellabes** [comment] 2021-11-10 01:17
Was a bit premature in closing this! Haven't actually merged the code yet 😅

**Closed** 2022-04-05 04:53 UTC
Labels: duplicate, enhancement
