### ISSUE TITLE
Update Documentation v1.0 README Release Candidate Status

### ISSUE THREAD

**Issue by RAbramson1** [dbt-labs/dbt-utils#763] opened 2023-01-27 16:32 UTC
### Describe the bug
The [README](https://github.com/dbt-labs/dbt-utils/tree/1.0.0#installation-instructions) states that dbt utils v1.0 is in release candidate status and that v.0.9.6 is the shipped version; however, it looks like that is an outdated status since the tags list 1.0.0, 1.0.0-rc1, 1.0.0-b1, and  1.0.0-b2.0

 v1.0 was released on December 5th (slack announcement [here](https://getdbt.slack.com/archives/CU4MRJ7QB/p1670290530211619)) with no notice regarding it being in release candidate status, so it seems likely that it is an oversight. 

### Steps to reproduce
- Review [README](https://github.com/dbt-labs/dbt-utils/tree/1.0.0#installation-instructions); ensure that the tag is set to v1.0
 
### Expected results
- The note regarding v1.0 still being in the release candidate status shouldn't appear.

### Screenshots and log output
Current README Documentation
![image](https://user-images.githubusercontent.com/7650373/215138298-bca773a1-f010-4835-8633-b4a7ad54e990.png)

Current Available Tags
![image](https://user-images.githubusercontent.com/7650373/215138768-736e09ee-ffd8-4072-b08a-579758aac16d.png)

### Additional context
The [hub](https://hub.getdbt.com/dbt-labs/dbt_utils/latest/) needs to be updated as well.

### Are you interested in contributing the fix?
I'm happy to submit a PR that will fix the issue.

**Comment by joellabes** [comment] 2023-01-28 03:09
Thanks for pointing this out @RAbramson1! this is a dupe of #740 and is fixed on the `main` branch. We can only change what is shown on the hub when we cut a new release, and I didn't think it was necessary to release v1.0.1 just to revise the readme. 

We have recently merged some other changes, so a new minor version of utils will also be coming at some point soon which will fully solve this.

**Closed by joellabes** 2023-01-28 03:09 UTC
Labels: bug, triage

**Comment by RAbramson1** [comment] 2023-01-30 18:38
> Thanks for pointing this out @RAbramson1! this is a dupe of #740 and is fixed on the `main` branch. We can only change what is shown on the hub when we cut a new release, and I didn't think it was necessary to release v1.0.1 just to revise the readme.
> 
> We have recently merged some other changes, so a new minor version of utils will also be coming at some point soon which will fully solve this.

Gotcha, thanks @joellabes !
